### ISSUE TITLE
Add support for intervention/image v3

### ISSUE THREAD

**Issue by Waterdhavian** [marshmallow-packages/nova-advanced-image#57]
Do you have plans to update to the v3 version of intervention/image?

I wanted to install your package but my project uses the v3 version already :)

**Comment by Waterdhavian** [comment]
I created a PR for it, sorry the typo in the branch name ;)

**Comment by stefvanesch** [comment]
@Waterdhavian thanks for the PR. We are tagging the new release now.

**Comment by stefvanesch** [comment]
Version 2.2.0 has been released.
